# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    # We'll use the single-file case for these runs
    NF_WORKFLOW_OPTS: "--sv --sample_name test_sample --ubam_sort_threads 1 --ubam_map_threads 2 --ref http://www.bio8.cs.hku.hk/clairs/quick_demo/ont/GRCh38_no_alt_chr17.fa --bam_control http://www.bio8.cs.hku.hk/clairs/quick_demo/ont/HCC1395BL_normal_chr17_demo.bam --bam_cancer http://www.bio8.cs.hku.hk/clairs/quick_demo/ont/HCC1395_tumor_chr17_demo.bam"
    CI_FLAVOUR: "new" # set to "classic" for old-style CI
    NF_IGNORE_PROCESSES: "getParams,getVersions,makeReport,summariseReads"


# Remove this block in downstream templates
singularity-run:
    tags: [] # no need for big ram
# end


docker-run:

    # Remove this directive in downstream templates
    tags: [] # no need for big ram

    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            # TODO: do we really need to run all from s3?
            - MATRIX_NAME: [
                "base"
                ]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #   being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "base"
          variables:
              NF_WORKFLOW_OPTS: "--sv --ubam_sort_threads 1 --ubam_map_threads 2 --bam_control http://www.bio8.cs.hku.hk/clairs/quick_demo/ont/HCC1395BL_normal_chr17_demo.bam --bam_cancer http://www.bio8.cs.hku.hk/clairs/quick_demo/ont/HCC1395_tumor_chr17_demo.bam --ref http://www.bio8.cs.hku.hk/clairs/quick_demo/ont/GRCh38_no_alt_chr17.fa"
